// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2esL2JOjEVWeZK2IlrAiAEXkd4YT4930',
    appId: '1:251803298171:web:818319eb3a6e420098b5de',
    messagingSenderId: '251803298171',
    projectId: 'tracker-flutter-bcefb',
    authDomain: 'tracker-flutter-bcefb.firebaseapp.com',
    storageBucket: 'tracker-flutter-bcefb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzU7IV80Hh_zgQNe54CIY31yNrCjWYQYA',
    appId: '1:251803298171:android:72a4a3e6a253471d98b5de',
    messagingSenderId: '251803298171',
    projectId: 'tracker-flutter-bcefb',
    storageBucket: 'tracker-flutter-bcefb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtj9tu5sBYTsr7TmpopFYdoZp6J1OmNOQ',
    appId: '1:251803298171:ios:331f6b050d2f613b98b5de',
    messagingSenderId: '251803298171',
    projectId: 'tracker-flutter-bcefb',
    storageBucket: 'tracker-flutter-bcefb.firebasestorage.app',
    iosBundleId: 'ma.ac.esisa.trackerFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtj9tu5sBYTsr7TmpopFYdoZp6J1OmNOQ',
    appId: '1:251803298171:ios:331f6b050d2f613b98b5de',
    messagingSenderId: '251803298171',
    projectId: 'tracker-flutter-bcefb',
    storageBucket: 'tracker-flutter-bcefb.firebasestorage.app',
    iosBundleId: 'ma.ac.esisa.trackerFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2esL2JOjEVWeZK2IlrAiAEXkd4YT4930',
    appId: '1:251803298171:web:2a945c0d89791ec298b5de',
    messagingSenderId: '251803298171',
    projectId: 'tracker-flutter-bcefb',
    authDomain: 'tracker-flutter-bcefb.firebaseapp.com',
    storageBucket: 'tracker-flutter-bcefb.firebasestorage.app',
  );
}
